apiVersion: apps/v1
kind: Deployment
metadata:
  name: oggstd19
  namespace: goldengate-standard
  creationTimestamp: null
  labels:
    app: oggstd19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oggstd19
  strategy: {}
  template:
    metadata:
      name: oggstd19
      creationTimestamp: null
      labels:
        app: oggstd19
    spec:
      volumes:
        - name: goldengate-standard-dirprm
          hostPath:
            path: /Users/markmixson/k8s-data/goldengate-standard/dirprm
        - name: goldengate-standard-dirdat
          hostPath:
            path: /Users/markmixson/k8s-data/goldengate-standard/dirdat
        - name: goldengate-standard-tns
          hostPath:
            path: /Users/markmixson/k8s-data/goldengate-standard/network
      containers:
      - image: oracle/goldengate-standard:19.1.0.0.4
        command: ["/bin/bash"]
        args: ["-c", "chown -R 54321:54321 /u01/app/ogg/dirdat && bash /runOracleGoldenGate.sh"]
        imagePullPolicy: Never
        name: oggstd19
        resources: {}
        ports:
        - containerPort: 7810
          hostPort: 7810
        volumeMounts:
          - name: goldengate-standard-dirprm
            mountPath: /u01/app/ogg/dirprm
          - name: goldengate-standard-dirdat
            mountPath: /u01/app/ogg/dirdat
          - name: goldengate-standard-tns
            mountPath: /network
        env:
          - name: OGG_ADMIN_PWD 
            value: Welcome1
          - name: TNS_ADMIN
            value: /network
          - name: PORT_BASE
            value: "7810"
          - name: LD_LIBRARY_PATH
            value: $ORACLE_HOME/lib:$OGG_HOME
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: oggstd19
  namespace: goldengate-standard
spec:
  selector:
    app: oggstd19
  ports:
  - protocol: TCP
    port: 7810
    targetPort: 7810
