apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-cat
  name: kafka-cat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cat
  template:
    metadata:
      labels:
        app: kafka-cat
    spec:
      containers:
        - name: kafka-cat
          image: edenhill/kafkacat:1.5.0
          command: ["/bin/sh"]
          args: ["-c", "trap : TERM INT; tail -f /dev/null"]
